MINE_COUNT = 20
GRID_SIZE = 14
CELL_SIZE = 50
CELL_BORDER_SIZE = 6

ROOT_WIDTH = GRID_SIZE * CELL_SIZE + GRID_SIZE * CELL_BORDER_SIZE
TOP_FRAME_WIDTH = ROOT_WIDTH
GAME_FRAME_WIDTH = ROOT_WIDTH

TOP_FRAME_HEIGHT = 60
ROOT_HEIGHT = ROOT_WIDTH + TOP_FRAME_HEIGHT
GAME_FRAME_HEIGHT = ROOT_HEIGHT - TOP_FRAME_HEIGHT

STARTED = False
OVER = False
